name: build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13.10
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'
    - name: npm install and run unittest
      run: |
        npm ci
        npm run test
      env:
        ROSTER_URL: ${{ secrets.ROSTER_URL_PR }}
        APP_ID: ${{ secrets.APP_ID_PR }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET_PR }}
        TASKER_APP_ID: ${{ secrets.TASKER_APP_ID }}
        CI: true
    - name: Build container and push to dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BA_ROSTER_URL: ${{ secrets.ROSTER_URL_PR }}
        BA_APP_ID: ${{ secrets.APP_ID_PR }}
        BA_WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET_PR }}
      with:
        name: devolutionfinland/tasker
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}
        dockerfile: Dockerfile
        tags: pr
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TASKER_HOST_PR }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PW_PR }}
        port: ${{ secrets.PORT }}
        script: |
          /snap/bin/docker stop $(/snap/bin/docker ps -a -q)
          /snap/bin/docker pull devolutionfinland/tasker:pr
          /snap/bin/docker run --rm -d -e WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET_PR }} -e APP_ID=${{ secrets.APP_ID_PR }} -e ROSTER_URL=${{ secrets.ROSTER_URL_PR }} -e TASKER_APP_ID=${{ secrets.TASKER_APP_ID }} -v $PWD/key.pem:/home/node/app/key.pem -p 80:8080 devolutionfinland/tasker:latest
